/*
 * Inventory Tracker API
 * The API that the Inventory Tracker clients communicate with
 *
 * OpenAPI spec version: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tk.jonathancowling.inventorytracker.clients.list.models

import java.util.Objects

class PartialItem(val id: String, val name: String?, val quantity: Int?) {

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }
        return if (other == null || javaClass != other.javaClass) {
            super.equals(other)
        } else hashCode() == other.hashCode()
    }

    override fun hashCode(): Int {
        return Objects.hash(id, name, quantity)
    }
}

